### ISSUE TITLE
cy.task() must only be invoked from the spec file or support file. - since Cypress v12.15.0

### ISSUE THREAD

**Issue by adrian-maciuc** [archfz/cypress-terminal-report#189]
Hey guys

This plugin helps me a lot but I have this new error since the latest upgrade of cypress to ver 12.15.0

`cy.task() must only be invoked from the spec file or support file. `

![Screenshot 2023-06-23 at 14 11 35](https://github.com/archfz/cypress-terminal-report/assets/106149016/5a9195e2-d274-484f-b260-d146a5ac3276)

Any suggestions?

**Comment by archfz** [comment]
Tried to reproduce this but cannot. Checkout https://github.com/archfz/cypress-terminal-report-demo it has the latest version of the dependencies. Try to make a fork and reproduce it. Otherwise provide more details.

**Comment by quipo** [comment]
We're having the same issue, after upgrading to Cypress 12.15.0:

```
CypressError: `cy.task()` must only be invoked from the spec file or support file.

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.

  From Your Spec Code:
      at Context.eval (webpack:///./node_modules/cypress-terminal-report/src/collector/LogCollectSimpleControl.js:68:0)
```

**Comment by ryanjduffy** [comment]
FYI - https://github.com/cypress-io/cypress/issues/27099 is probably the cause. It broke our plugin (`@replayio/cypress`) as well and we're also use `Cypress.backend("task", ...)` (which I discovered from this project!).

**Comment by ryanjduffy** [comment]
This [diff](https://github.com/cypress-io/cypress/commit/89f0fb64650d1795a912773b5c0660d1aceea0bc#diff-82872783c0d67ee302508296e4c1991c88e3d86fa2d88f21b7097e8fe7b927e5R32) shows the new format for 12.15 (and beyond, presumably)

<img width="562" alt="image" src="https://github.com/archfz/cypress-terminal-report/assets/788456/87d84e38-4eee-4723-990e-140af5130b8f">

**Comment by archfz** [comment]
Thank you @ryanjduffy for pointing that out. The question still remains why I cannot reproduce this, for example in the demo repo.

**Comment by quipo** [comment]
Fixed in Cypress 12.16.0: https://docs.cypress.io/guides/references/changelog#12-16-0

**Comment by vpume** [comment]
The problem is still there, even with Cypress 12.16.0. Downgrading to Cypress 12.14.0 helped, however.

**Comment by Ido112** [comment]
Solved on Cypress 12.16.0 for me

**Comment by adrian-maciuc** [comment]
Can confirm, fixed in v12.16.0 thank you everyone.

**Comment by archfz** [comment]
@vpume Does it still reproduce for you? If yes please open a new issue and detail your case.
