### ISSUE TITLE
'Domain exception: log stack null'

### ISSUE THREAD

**Issue by FFdhorkin** [archfz/cypress-terminal-report#98]
Not sure if this was happening before and I just didn't notice, but the log reporter appears to be misbehaving when run in the GUI.

This only seems to happen for some spec files. I don't know for sure, but it appears to be an issue with nested `describe()` blocks and `cypress-terminal-report`, though I suppose that could be a coincidence. Specs that have multiple non-nested describes don't output this error, but both of my specs with nested describes are producing this.

Also unsure whether relevant, but I'm using Cypress 5.6.0 on Linux (technically, WSL2)

![image](https://user-images.githubusercontent.com/59899746/117850182-ea606d00-b239-11eb-88c6-f40fbe94196f.png)

Running the same suite in the terminal doesn't seem to cause any problems (or at least, they aren't printed).

![image](https://user-images.githubusercontent.com/59899746/117851274-00226200-b23b-11eb-9365-ba418103912a.png)

**Comment by FFdhorkin** [comment]
in plugins: `installLogsPrinter(on, { printLogsToConsole: 'onFail', includeSuccessfulHookLogs: false });`
in support: `installLogsPrinter({ enableExtendedCollector: true });`

I've created an example spec that reproduces, as well. Looks like you need BOTH nested describes AND an afterEach in order for the duplicates/null errors to appear.

```JavaScript
describe('Nested log Test', () => {
    afterEach(() => {
    });

    it('test1', () => {
    });

    it('test2', () => {
    });

    it('test3', () => {
    });

    describe('Nested', () => {
        it('nestTest1', () => {
        });

        it('nestTest2', () => {
        });

        it('nestTest3', () => {
        });
    });
});
```

**Comment by archfz** [comment]
Fix released in 3.1.2.

**Comment by FFdhorkin** [comment]
This issue is still present, though the minimum spec to repro it is slightly different now. If the nested describe **also** has an afterEach hook, the error comes back.

```
    describe('Nested log Test', () => {
        afterEach(() => {});

        it('test1', () => {
        });

        it('test2', () => {
        });

        it('test3', () => {
        });

        describe('Nested', () => {
            afterEach(() => {});

            it('nestTest1', () => {
            });

            it('nestTest2', () => {
            });

            it('nestTest3', () => {
            });
        });
    });
```

**Comment by archfz** [comment]
Released in 3.2.1.

**Comment by FFdhorkin** [comment]
Confirmed :) thank you!

**Comment by FFdhorkin** [comment]
Looks like a regression has come up... 3.2.1 is working, but 3.3.0 and newer have this problem again.
